name: shard
description: "A new Flutter app for sharing boardgames."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  barcode_scan2: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
      - asset: assets/fonts/RubikDoodleShadow-Regular.ttf
    - family: Asap
      fonts:
      - asset: assets/fonts/AsapCondensed-Regular.ttf

